# Generated by Django 6.0.7 on 2026-08-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_dailyproduction_rate_per_piece_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproduction',
            name='rate_per_piece',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
