# Generated by Django 6.0.7 on 2026-08-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_dailyproduction_rate_per_piece'),
        ('products', '0006_remove_product_size_product_available_sizes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProductRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_piece', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rates', to='employees.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_rates', to='products.product')),
            ],
            options={
                'ordering': ['employee__name', 'product__name'],
                'unique_together': {('employee', 'product')},
            },
        ),
    ]
