# Generated by Django 6.0.7 on 2026-08-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeeproductrate'),
        ('products', '0006_remove_product_size_product_available_sizes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeproductrate',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='employeeproductrate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='employeeproductrate',
            constraint=models.UniqueConstraint(fields=('employee', 'product'), name='unique_employee_product_rate'),
        ),
    ]
