# Generated by Django 6.0.7 on 2026-08-14 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_remove_product_size_product_available_sizes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('alteration_date', models.DateField(default=django.utils.timezone.now)),
                ('custom_size', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alterations', to='products.product')),
            ],
        ),
    ]
