# Generated by Django 6.0.7 on 2026-08-14 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alterations', '0002_alteration_advance_amount_and_more'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alteration',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alterations', to='branches.branch'),
            preserve_default=False,
        ),
    ]
