# Generated by Django 6.1 on 2026-09-05 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alterations', '0003_alteration_branch'),
        ('employees', '0005_alter_employeeproductrate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alteration',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alterations', to='employees.employee'),
        ),
    ]
