# Generated by Django 6.1 on 2026-09-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alterations', '0004_alteration_assigned_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='alteration',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='alteration',
            name='delivered_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='alteration',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alteration',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alteration',
            name='delivery_payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Online', 'Online'), ('Cheque', 'Cheque'), ('POS', 'POS')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alteration',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alteration',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alteration',
            name='expected_delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alteration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivery', 'Delivery'), ('Cancel', 'Cancel')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='alteration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='alteration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
