# Generated by Django 6.0.7 on 2026-07-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0002_migrate_old_daybook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
