# Generated by Django 6.0.7 on 2026-07-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0003_alter_daybook_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='daybook',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Online', 'Online'), ('Cheque', 'Cheque'), ('POS', 'POS')], default='Cash', max_length=20),
        ),
    ]
