# Generated by Django 6.0.7 on 2026-08-08 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0004_daybook_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
