# Generated by Django 6.0.7 on 2026-08-14 14:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('daybook', '0005_alter_daybook_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daybook_entries', to='branches.branch'),
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateField(default=django.utils.timezone.now)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_bank', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balance', to='branches.branch')),
            ],
        ),
    ]
