# Generated by Django 6.0.7 on 2026-07-14 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_type', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cutting', 'Cutting'), ('Stitching', 'Stitching'), ('Ready', 'Ready'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
