# Generated by Django 6.0.7 on 2026-07-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_remarks_order_advance_paid_order_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='remarks',
        ),
    ]
