# Generated by Django 6.0.7 on 2026-08-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dress_type',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('Pant', 'Pant'), ('Kurta', 'Kurta'), ('Blazer', 'Blazer'), ('Safari', 'Safari'), ('Coat', 'Coat'), ('Jubba', 'Jubba'), ('Others', 'Others')], max_length=50),
        ),
    ]
