# Generated by Django 6.0.7 on 2026-08-13 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_delivered_by_order_delivered_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='advance_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='advance_payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Online', 'Online'), ('Cheque', 'Cheque'), ('POS', 'POS')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Advance', 'Advance'), ('Balance Payment', 'Balance Payment')], default='Balance Payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
    ]
