# Generated by Django 6.0.7 on 2026-08-14 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_advance_paid_order_advance_payment_mode_and_more'),
        ('products', '0006_remove_product_size_product_available_sizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
