# Generated by Django 6.1 on 2026-09-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orderitem_item_name_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=20),
        ),
    ]
