# Generated by Django 6.1 on 2026-09-30 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('employees', '0005_alter_employeeproductrate_options_and_more'),
        ('orders', '0011_stockprocessing'),
        ('products', '0007_stockprocessing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprocessing',
            name='order',
        ),
        migrations.AddField(
            model_name='stockprocessing',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockprocessing',
            name='expected_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockprocessing',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Online', 'Online'), ('Cheque', 'Cheque'), ('POS', 'POS')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='stockprocessing',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_processing', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockprocessing',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stockprocessing',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockprocessing',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stockprocessing',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockprocessing',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_processing', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='stockprocessing',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_processing', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='stockprocessing',
            name='process_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('EMBROIDERY', 'Embroidery'), ('PRINTING', 'Printing'), ('STITCHING', 'Stitching'), ('ALTERATION', 'Alteration'), ('OTHER', 'Other')], default='PURCHASE', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockprocessing',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
