# Generated by Django 6.0.7 on 2026-08-10 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_selling_price_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='branch_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.branchproduct'),
        ),
    ]
