# Generated by Django 6.1 on 2026-09-28 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('employees', '0005_alter_employeeproductrate_options_and_more'),
        ('products', '0006_remove_product_size_product_available_sizes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('STITCHING', 'Stitching'), ('EMBROIDERY', 'Embroidery'), ('ALTERATION', 'Alteration'), ('OTHER', 'Other')], max_length=20)),
                ('input_quantity', models.PositiveIntegerField(default=0)),
                ('issued_quantity', models.PositiveIntegerField(default=0)),
                ('output_quantity', models.PositiveIntegerField(default=0)),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('expected_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_processings', to='branches.branch')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_processings', to='employees.employee')),
                ('input_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_inputs', to='products.product')),
                ('output_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processing_outputs', to='products.product')),
            ],
        ),
    ]
