# Generated by Django 6.1 on 2026-09-30 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_stockprocessing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprocessing',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='stockprocessing',
            name='input_product',
        ),
        migrations.RemoveField(
            model_name='stockprocessing',
            name='input_quantity',
        ),
        migrations.RemoveField(
            model_name='stockprocessing',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='stockprocessing',
            name='issued_quantity',
        ),
        migrations.RemoveField(
            model_name='stockprocessing',
            name='output_product',
        ),
        migrations.RemoveField(
            model_name='stockprocessing',
            name='output_quantity',
        ),
        migrations.RemoveField(
            model_name='stockprocessing',
            name='returned_quantity',
        ),
        migrations.AddField(
            model_name='stockprocessing',
            name='expected_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockprocessing',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Online', 'Online'), ('Cheque', 'Cheque'), ('POS', 'POS')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='stockprocessing',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_processings', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockprocessing',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stockprocessing',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockprocessing',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stockprocessing',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockprocessing',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockprocessing',
            name='process_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('EMBROIDERY', 'Embroidery'), ('PRINTING', 'Printing'), ('STITCHING', 'Stitching'), ('ALTERATION', 'Alteration'), ('OTHER', 'Other')], default='PURCHASE', max_length=20),
        ),
    ]
