# Generated by Django 6.1 on 2026-10-03 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employeeproductrate_options_and_more'),
        ('products', '0008_remove_stockprocessing_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='movement_type',
            field=models.CharField(choices=[('TRANSFER', 'Stock Transfer'), ('PRODUCTION', 'Production'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment')], default='TRANSFER', max_length=20),
        ),
    ]
